# Generated by Django 4.2.20 on 2025-05-29 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_alter_post_content_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourited_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
