# Generated by Django 4.2.20 on 2025-05-29 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_alter_favourite_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user", "post")},
        ),
    ]
