# Generated by Django 4.2.20 on 2025-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_favourite_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="continent",
            field=models.IntegerField(
                choices=[
                    (0, "South/Central America"),
                    (1, "North America"),
                    (2, "Europe"),
                    (3, "Africa"),
                    (4, "Asia"),
                    (5, "Australia"),
                ],
                default=2,
            ),
        ),
    ]
