# Generated by Django 4.2.20 on 2025-06-01 12:26

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_continent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder",
                max_length=255,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
